# Generated by Django 3.2.9 on 2022-02-05 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0019_remove_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default=0, upload_to='images'),
            preserve_default=False,
        ),
    ]
